# Generated by Django 6.0 on 2025-12-16 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casino', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Player',
        ),
    ]
